# CFG PRM 1

# mlrMBO settings

# Total iterations
PROPOSE_POINTS=${PROPOSE_POINTS:-100}
MAX_CONCURRENT_EVALUATIONS=${MAX_CONCURRENT_EVALUATIONS:-100}
MAX_ITERATIONS=${MAX_ITERATIONS:-10}
MAX_BUDGET=${MAX_BUDGET:-1000}
DESIGN_SIZE=${DESIGN_SIZE:-100}
PARAM_SET_FILE=${PARAM_SET_FILE:-$EMEWS_PROJECT_ROOT/data/hps_space.R}
MODEL_NAME="combo"




